"""add ingestion audit table

Revision ID: f4eb40cdd6e0
Revises: c970a8ba8b3d
Create Date: 2025-05-06 23:52:39.759247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4eb40cdd6e0'
down_revision: Union[str, None] = 'c970a8ba8b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_audit_id'), 'ingestion_audit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_audit_id'), table_name='ingestion_audit')
    op.drop_table('ingestion_audit')
    # ### end Alembic commands ###
